create table flags (channel_id INTEGER NOT NULL, flag TEXT NOT NULL, PRIMARY KEY (channel_id, flag))
create table flags_description (flag TEXT NOT NULL PRIMARY KEY, description TEXT NOT NULL)
create table runs (run_num INTEGER NOT NULL, run_type TEXT NOT NULL, comment TEXT DEFAULT "")
create table all_channels (channel_id INTEGER PRIMARY KEY NOT NULL, location TEXT)
create table data_pedestal_hvon (channel_id INTEGER, key TEXT, value REAL, PRIMARY KEY (channel_id, key))
create table data_testpulse (channel_id INTEGER, key TEXT, value REAL, PRIMARY KEY (channel_id, key))
create table data_laser (channel_id INTEGER, key TEXT, value REAL, PRIMARY KEY (channel_id, key))
create table data_pedestal_hvoff (channel_id INTEGER, key TEXT, value REAL, PRIMARY KEY (channel_id, key))
create table options (name TEXT NOT NULL PRIMARY KEY, value)
create index ichannels on all_channels (channel_id)
create index ipon on data_pedestal_hvon (channel_id, key)
create index ipoff on data_pedestal_hvoff (channel_id, key)
create index itp on data_testpulse (channel_id, key)
create index il on data_laser (channel_id, key)
create index iflags on flags (channel_id)
